main:
  - identifier: "home"
    name: "Home"
    url: "/"
    weight: -100
  - identifier: "azurePowerShell"
    name: "Azure Scripts"
    url: "/AzurePowerShell/"
    weight: 10
  - identifier: "about"
    name: "About"
    url: "/about/"
    weight: 50
  - identifier: "github"
    name: "Github"
    url: "https://github.com/gkarwchan/hugoblogsource"
    weight: 100